export const furnitureData = [
  {
    id: 1,
    headName: "Սեղաններ",
    name: "Կոդ 000001",
    url: "/furniture/livingRoom/1",
    imageUrl: "",
    images: [],
    description: "Loft ոճի կահույք",
    price: "$500",
  },
  {
    id: 2,
    name: "Կոդ 000002",
    url: "/furniture/livingRoom/2",
    imageUrl: "",
    images: [],
    description: "Փափուկ կահույք",
    price: "$300",
  },
  {
    id: 3,
    name: "Կոդ 000003",
    url: "/furniture/livingRoom/3",
    imageUrl: "",
    images: [],
    description: "Բազմոց",
    price: "$250",
  },
  {
    id: 4,
    name: "Կոդ 000004",
    url: "/furniture/livingRoom/4",
    imageUrl: "",
    images: [],
    description: "Բազկաթոռ",
    price: "$700",
  },
];