export const furnitureData = [
  {
    id: 1,
    name: "Սպիտակ գրատախտակ",
    url: "/metal/whiteboard/1",
    imageUrl: "/images/metal/whiteboard/whiteboard1.jpg",
    price: "150000 դր",
    description: "Սպիտակ գրատախտակ մագնիսական մակերեսով",
    type: "Սպիտակ",
    isAvailable: true
  },
  {
    id: 2,
    name: "Սպիտակ գրատախտակ մեծ",
    url: "/metal/whiteboard/2",
    imageUrl: "/images/metal/whiteboard/whiteboard2.jpg",
    price: "200000 դր",
    description: "Մեծ սպիտակ գրատախտակ մագնիսական մակերեսով",
    type: "Սպիտակ",
    isAvailable: true
  },
  {
    id: 3,
    name: "Սպիտակ գրատախտակ փոքր",
    url: "/metal/whiteboard/3",
    imageUrl: "/images/metal/whiteboard/whiteboard3.jpg",
    price: "100000 դր",
    description: "Փոքր սպիտակ գրատախտակ մագնիսական մակերեսով",
    type: "Սպիտակ",
    isAvailable: true
  },
  {
    id: 4,
    name: "Գրատախտակ 4",
    url: "/metal/whiteboard/4",
    description: "Մագնիսական գրատախտակ 180x240 սմ",
    price: 95000,
    type: "Մագնիսական",
    imageUrl: "https://res.cloudinary.com/dpbsyoxw8/image/upload/v1747646123/furniture/whiteboard4.png",
    isAvailable: true,
  },
  {
    id: 5,
    name: "Գրատախտակ 5",
    url: "/metal/whiteboard/5",
    description: "Մագնիսական գրատախտակ 200x300 սմ",
    price: 120000,
    type: "Մագնիսական",
    imageUrl: "https://res.cloudinary.com/dpbsyoxw8/image/upload/v1747646123/furniture/whiteboard5.png",
    isAvailable: true,
  },
  {
    id: 6,
    name: "Գրատախտակ 6",
    url: "/metal/whiteboard/6",
    description: "Մագնիսական գրատախտակ 240x360 սմ",
    price: 150000,
    type: "Մագնիսական",
    imageUrl: "https://res.cloudinary.com/dpbsyoxw8/image/upload/v1747646123/furniture/whiteboard6.png",
    isAvailable: true,
  },
]; 